In [18]:
import numpy as np
import os
import cv2
from keras.models import Sequential
from keras.layers import Dense, Activation, Convolution2D, Flatten, MaxPooling2D
from keras.utils import np_utils

In [19]:
dataset_path = './data/'

In [20]:
face_data = []
labels = []
class_id = 0

In [21]:
for ix in os.listdir(dataset_path):
    if ix.endswith('.npy'):
        data_item = np.load(dataset_path + ix)
        face_data.append(data_item)

        target = class_id * np.ones((data_item.shape[0],))
        class_id += 1
        labels.append(target)
face_dataset = np.concatenate(face_data, axis=0)
face_labels = np.concatenate(labels, axis=0).reshape((-1, 1))
print face_labels.shape
print face_dataset.shape
print face_labels
print face_dataset

(60, 1)
(60, 10000)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]]
[[ 71  75  69 ...  19  12  13]
 [ 75  73  71 ...  19  22  26]
 [ 72  72  74 ...  19  25  25]
 ...
 [151 151 150 ... 151 155 158]
 [152 151 150 ... 162 168 171]
 [ 59  17  10 ... 175 176 180]]


In [22]:
trainset = np.concatenate((face_dataset, face_labels), axis=1)
print trainset.shape
print trainset

(60, 10001)
[[ 71.  75.  69. ...  12.  13.   0.]
 [ 75.  73.  71. ...  22.  26.   0.]
 [ 72.  72.  74. ...  25.  25.   0.]
 ...
 [151. 151. 150. ... 155. 158.   2.]
 [152. 151. 150. ... 168. 171.   2.]
 [ 59.  17.  10. ... 176. 180.   2.]]


In [23]:
face_labels = np_utils.to_categorical(face_labels)
print face_labels

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [24]:
face_dataset = face_dataset/255.0

In [25]:
print face_dataset

[[0.27843137 0.29411765 0.27058824 ... 0.0745098  0.04705882 0.05098039]
 [0.29411765 0.28627451 0.27843137 ... 0.0745098  0.08627451 0.10196078]
 [0.28235294 0.28235294 0.29019608 ... 0.0745098  0.09803922 0.09803922]
 ...
 [0.59215686 0.59215686 0.58823529 ... 0.59215686 0.60784314 0.61960784]
 [0.59607843 0.59215686 0.58823529 ... 0.63529412 0.65882353 0.67058824]
 [0.23137255 0.06666667 0.03921569 ... 0.68627451 0.69019608 0.70588235]]


In [26]:
face_dataset = face_dataset.reshape((-1,100,100,1))
print face_dataset

[[[[0.27843137]
   [0.29411765]
   [0.27058824]
   ...
   [0.2       ]
   [0.20392157]
   [0.21960784]]

  [[0.29019608]
   [0.29411765]
   [0.27058824]
   ...
   [0.18823529]
   [0.19607843]
   [0.22352941]]

  [[0.27843137]
   [0.29803922]
   [0.29019608]
   ...
   [0.18039216]
   [0.19215686]
   [0.23921569]]

  ...

  [[0.17647059]
   [0.18039216]
   [0.16078431]
   ...
   [0.09411765]
   [0.08627451]
   [0.07058824]]

  [[0.1254902 ]
   [0.15686275]
   [0.17647059]
   ...
   [0.10196078]
   [0.07058824]
   [0.07058824]]

  [[0.14117647]
   [0.11764706]
   [0.15686275]
   ...
   [0.0745098 ]
   [0.04705882]
   [0.05098039]]]


 [[[0.29411765]
   [0.28627451]
   [0.27843137]
   ...
   [0.23529412]
   [0.20784314]
   [0.22745098]]

  [[0.28235294]
   [0.28235294]
   [0.26666667]
   ...
   [0.22745098]
   [0.21176471]
   [0.21176471]]

  [[0.27843137]
   [0.28627451]
   [0.27058824]
   ...
   [0.24313725]
   [0.21960784]
   [0.19607843]]

  ...

  [[0.14509804]
   [0.17254902]
   [0.1

In [30]:
model = Sequential()

## Shape Here - (b, 100, 100, 1)
model.add(Convolution2D(32, kernel_size=(10, 10), input_shape=(100, 100, 1)))
model.add(Activation('relu'))
## Shape Here - (b, 91, 91, 32)
model.add(Convolution2D(16, kernel_size=(10, 10)))
model.add(Activation('relu'))
## Shape Here - (b, 82, 82, 16)
model.add(MaxPooling2D(pool_size=(2, 2)))
## Shape Here - (b, 41, 41, 16)
model.add(Convolution2D(8, (22, 22)))
model.add(Activation('relu'))
## Shape Here - (b, 20, 20, 8)
model.add(Convolution2D(8, (13, 13)))
model.add(Activation('relu'))
## Shape Here - (b, 8, 8, 8)
model.add(Flatten())
## Shape Here - (b, 512)
model.add(Dense(256))
model.add(Activation('relu'))
## Shape Here - (b, 256)
model.add(Dense(3))
## Shape Here - (b, 10)
model.add(Activation('softmax'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_9 (Conv2D)            (None, 91, 91, 32)        3232      
_________________________________________________________________
activation_13 (Activation)   (None, 91, 91, 32)        0         
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 82, 82, 16)        51216     
_________________________________________________________________
activation_14 (Activation)   (None, 82, 82, 16)        0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 41, 41, 16)        0         
_________________________________________________________________
conv2d_11 (Conv2D)           (None, 20, 20, 8)         61960     
_________________________________________________________________
activation_15 (Activation)   (None, 20, 20, 8)         0         
__________

In [31]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [32]:
model.fit(face_dataset, face_labels, epochs=20, batch_size=8)

Epoch 1/20
60/60 [==============================] - 9s 149ms/step - loss: 1.1370 - acc: 0.3000
Epoch 2/20
60/60 [==============================] - 8s 136ms/step - loss: 1.1031 - acc: 0.3000
Epoch 3/20
60/60 [==============================] - 8s 137ms/step - loss: 1.0607 - acc: 0.5667
Epoch 4/20
60/60 [==============================] - 8s 141ms/step - loss: 0.6644 - acc: 0.8000
Epoch 5/20
60/60 [==============================] - 8s 137ms/step - loss: 0.1267 - acc: 0.9333
Epoch 6/20
60/60 [==============================] - 8s 137ms/step - loss: 0.0230 - acc: 0.9833
Epoch 7/20
60/60 [==============================] - 9s 146ms/step - loss: 0.7435 - acc: 0.8167
Epoch 8/20
60/60 [==============================] - 10s 166ms/step - loss: 0.4703 - acc: 0.8167
Epoch 9/20
60/60 [==============================] - 9s 157ms/step - loss: 0.1389 - acc: 0.9833
Epoch 10/20
60/60 [==============================] - 8s 137ms/step - loss: 0.0047 - acc: 1.0000
Epoch 11/20
60/60 [=============================

In [33]:
model.save('Face_Recogizer.h5')