In [1]:
import cv2
import numpy as np
from keras.models import load_model

Using TensorFlow backend.


In [2]:
model = load_model('Face_Recogizer.h5')
face_cascade = cv2.CascadeClassifier('./haarcascade_frontalface_alt.xml')

In [3]:
names = {
    0 : 'bhumika',
    1 : 'shivang',
    2 : 'suransh'
}

In [4]:
def predict(cur):
    fin_img = cv2.resize(cur, (100,100) )
    fin_img = np.array(fin_img)
    fin_img = fin_img.reshape( (1,100,100,1) )
    fin_img = fin_img/255.0
    result = model.predict( fin_img )
    print(result)
    num = np.argmax( result[0] )
    return num

In [5]:
cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    if ret==False:
        continue
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for face in faces[:1]:
        x,y,w,h = face
        offset = 7
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset]
        face_section = cv2.resize(face_section,(100,100))
        out = predict(cv2.cvtColor(face_section,cv2.COLOR_BGR2GRAY))
        cv2.rectangle(frame, (x,y), (x+w,y+h), (255,255,255), 2)
        cv2.putText(frame, names[int(out)],(x,y-10), cv2.FONT_HERSHEY_SIMPLEX, 1,(0,255,0),2,cv2.LINE_AA)
    cv2.imshow("Faces", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

[[1.7973198e-08 9.9999881e-01 1.2467243e-06]]
[[0.54680526 0.44217378 0.01102093]]
[[8.6127967e-04 9.9502891e-01 4.1098837e-03]]
[[2.2924786e-08 9.9996197e-01 3.8080223e-05]]
[[1.4829628e-08 9.9999738e-01 2.6353480e-06]]
[[5.4821312e-09 9.9999857e-01 1.4122708e-06]]
[[7.4777118e-09 9.9999905e-01 9.8331770e-07]]
[[3.891289e-09 9.999995e-01 5.361495e-07]]
[[7.4072887e-10 9.9999952e-01 5.0496010e-07]]
[[2.9457028e-10 9.9999976e-01 2.0025509e-07]]
[[1.505039e-11 9.999994e-01 6.016908e-07]]
[[2.7315194e-11 9.9999988e-01 1.5958575e-07]]
[[2.5902167e-12 9.9999976e-01 2.3108139e-07]]
[[2.2607635e-11 1.0000000e+00 4.6341849e-08]]
[[1.8816294e-12 9.9999928e-01 6.9480751e-07]]
[[1.9591954e-12 9.9999928e-01 7.0037919e-07]]
[[7.9448939e-12 9.9999917e-01 7.7523941e-07]]
[[5.0071223e-12 9.9999905e-01 9.1936744e-07]]
[[1.6583064e-10 9.9999976e-01 2.2412731e-07]]
[[1.8208002e-10 9.9999988e-01 1.1131492e-07]]
[[4.167438e-10 9.999994e-01 6.477486e-07]]
[[5.1676841e-07 9.9997878e-01 2.0697456e-05]]
[[1.58

[[1.4539856e-04 9.9974352e-01 1.1110363e-04]]
[[6.334163e-06 9.991698e-01 8.239091e-04]]
[[4.1323560e-06 9.9944502e-01 5.5084634e-04]]
[[3.2527543e-05 9.9839753e-01 1.5699815e-03]]
[[4.357950e-05 9.671746e-01 3.278181e-02]]
[[8.1475475e-05 9.9284488e-01 7.0737321e-03]]
[[7.250961e-04 9.916226e-01 7.652197e-03]]
[[3.6627325e-04 9.8362410e-01 1.6009599e-02]]
[[0.00114879 0.8808631  0.11798818]]
[[0.01403569 0.8533505  0.13261372]]
[[0.23526853 0.6750877  0.08964375]]
[[0.46664804 0.3867364  0.14661552]]
[[0.31613353 0.50771934 0.17614713]]
[[0.16142325 0.2713928  0.567184  ]]
[[0.41691345 0.0983261  0.4847604 ]]
[[0.4338383  0.00729338 0.55886835]]
[[0.05413396 0.0036381  0.9422279 ]]
[[0.30974492 0.00344134 0.6868138 ]]
[[0.9880419  0.00643445 0.00552376]]
[[0.65655017 0.02456932 0.31888056]]
[[0.02050785 0.00215215 0.97734   ]]
[[0.69632524 0.23759326 0.0660815 ]]
[[0.03450514 0.21097092 0.7545239 ]]
[[0.01112764 0.00214956 0.98672277]]
[[1.8493904e-02 9.1279863e-04 9.8059332e-01]]
[[7

[[0.03065063 0.9133024  0.05604692]]
[[0.14316098 0.8490463  0.0077927 ]]
[[0.03890001 0.9578768  0.00322322]]
[[0.10536592 0.863171   0.0314631 ]]
[[0.73870134 0.2590739  0.00222473]]
[[0.5062497  0.47603112 0.01771916]]
[[0.13577618 0.84549534 0.01872845]]
[[0.30127287 0.68495697 0.01377018]]
[[0.90266263 0.09617847 0.00115887]]
[[0.08339611 0.9140966  0.00250726]]
[[0.18437469 0.7934016  0.0222238 ]]
[[0.22600785 0.7706621  0.00333001]]
[[0.00159501 0.9743009  0.02410402]]
[[0.03425356 0.96284944 0.00289701]]
[[0.83374053 0.16447107 0.00178845]]
[[0.5051756  0.47425804 0.02056635]]
[[0.03427932 0.9428839  0.02283679]]
[[0.27914077 0.711444   0.00941521]]
[[9.7579473e-01 2.3314815e-02 8.9040300e-04]]
[[0.20004009 0.7223188  0.07764103]]
[[0.00967577 0.92531633 0.06500794]]
[[7.9212677e-01 2.0729618e-01 5.7705771e-04]]
[[0.01684465 0.9346871  0.04846826]]
[[0.96699274 0.03181871 0.00118851]]
[[0.00532279 0.9809871  0.01369015]]
[[0.10517947 0.8625007  0.03231985]]
[[0.01885329 0.90921

-1