In [1]:
import cv2
import os
import numpy as np
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [2]:
names = {
    0 : 'bhumika',
    1 : 'shivang',
    2 : 'suransh'
}

In [3]:
face_data = []
labels = []
class_id = 0
dataset_path = './data/'
face_cascade = cv2.CascadeClassifier('./haarcascade_frontalface_alt.xml')

In [4]:
for ix in os.listdir(dataset_path):
    if ix.endswith('.npy'):
        print ix
        data_item = np.load(dataset_path + ix)
        face_data.append(data_item)

        target = class_id * np.ones((data_item.shape[0],))
        class_id += 1
        labels.append(target)
face_dataset = np.concatenate(face_data, axis=0)
face_labels = np.concatenate(labels, axis=0).reshape((-1, 1))
print face_labels.shape
print face_dataset.shape
print face_labels
print face_dataset

bhumika.npy
shivang.npy
suransh.npy
(3028, 1)
(3028, 10000)
[[0.]
 [0.]
 [0.]
 ...
 [2.]
 [2.]
 [2.]]
[[ 43  45  43 ...  25  31  32]
 [ 49  48  52 ...  51  53  58]
 [ 53  53  53 ...  36  74  81]
 ...
 [141 144 146 ...  49  51  50]
 [140 142 147 ...  50  51  50]
 [126 135 140 ...  50  50  52]]


In [5]:
clf = SVC()
clf.fit(face_dataset,face_labels)
# neigh = KNeighborsClassifier(n_neighbors=3)
# neigh.fit(face_dataset,face_labels) 

/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
print clf.score(face_dataset,face_labels)

1.0


In [7]:
cap = cv2.VideoCapture(0)
while True:
    ret, frame = cap.read()
    if ret==False:
        continue
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for face in faces[:1]:
        x,y,w,h = face
        offset = 7
        face_section = frame[y-offset:y+h+offset,x-offset:x+w+offset]
        face_section = cv2.resize(face_section,(100,100))
        face_section = cv2.cvtColor(face_section,cv2.COLOR_BGR2GRAY)
        out = clf.predict(face_section.reshape((1,-1)))
        cv2.rectangle(frame, (x,y), (x+w,y+h), (255,255,255), 2)
        cv2.putText(frame, names[int(out)],(x,y-10), cv2.FONT_HERSHEY_SIMPLEX, 1,(0,255,0),2,cv2.LINE_AA)
    cv2.imshow("Faces", frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1